services:
  - type: worker
    name: graker-scheduler
    env: node
    plan: starter
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: SUPABASE_URL
        fromDatabase:
          name: graker-db
          property: connectionString
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: SCHEDULER_KEY
        sync: false
